// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextInspectionItem = { index: bigint,
/**
 * Bounded serialized response item type tag.
 */
kind: string,
/**
 * Bounded serialized role when the item has one.
 */
role: string | null,
/**
 * Size of the complete serialized item, including undisclosed content.
 */
serializedBytes: bigint, };
