// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextContentDisclosure } from "./ContextContentDisclosure";
import type { ContextInspectionCollection } from "./ContextInspectionCollection";
import type { ContextInspectionLimits } from "./ContextInspectionLimits";
import type { ContextNormalizationSummary } from "./ContextNormalizationSummary";
import type { ModelRequestInspection } from "./ModelRequestInspection";

export type ContextInspectionSnapshot = {
/**
 * History rewrite generation from the live context manager.
 */
historyVersion: bigint, contentDisclosure: ContextContentDisclosure, appliedLimits: ContextInspectionLimits,
/**
 * Current history before production prompt normalization.
 */
raw: ContextInspectionCollection,
/**
 * Current history after production prompt normalization.
 */
normalized: ContextInspectionCollection, normalization: ContextNormalizationSummary,
/**
 * Latest request attempt and latest request sent at the transport boundary.
 */
request: ModelRequestInspection, };
