// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextNormalizationSummary = {
/**
 * Items with identical complete serialization in both collections, counted as a multiset.
 */
unchangedItems: bigint, rawOnlyItems: bigint, normalizedOnlyItems: bigint,
/**
 * Whether normalization changed item identity, count, or order.
 */
changed: boolean, };
