// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextInspectionItem } from "./ContextInspectionItem";

export type ContextInspectionCollection = {
/**
 * Versioned SHA-256 fingerprint of all complete serialized items in order.
 */
fingerprint: string, totalItems: bigint, representedItems: bigint, omittedItems: bigint,
/**
 * Sum of complete serialized item sizes, including undisclosed content.
 */
totalSerializedBytes: bigint, items: Array<ContextInspectionItem>, };
