// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRequestSnapshot } from "./ModelRequestSnapshot";

export type ModelRequestInspection = { latestAttempt: ModelRequestSnapshot | null, lastActual: ModelRequestSnapshot | null,
/**
 * Whether current normalized history exactly matches `lastActual.normalizedInput`.
 */
currentNormalizedMatchesLastActual: boolean | null, };
