// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextInspectionCollection } from "./ContextInspectionCollection";
import type { ModelRequestAttemptStatus } from "./ModelRequestAttemptStatus";
import type { ModelRequestComponentSummary } from "./ModelRequestComponentSummary";
import type { ModelRequestTransport } from "./ModelRequestTransport";
import type { ModelRequestValueCollectionSummary } from "./ModelRequestValueCollectionSummary";

export type ModelRequestSnapshot = { sequence: bigint,
/**
 * Unix timestamp in seconds when the request was prepared.
 */
capturedAt: bigint, status: ModelRequestAttemptStatus, transport: ModelRequestTransport,
/**
 * Whether the WebSocket transport sent a delta with `previousResponseId`.
 */
transportUsesDelta: boolean,
/**
 * Whether the WebSocket connection was reused. Always false for HTTP.
 */
connectionReused: boolean, transportInputItems: bigint, model: string, provider: string,
/**
 * Identity and size of the complete logical request, not a WebSocket delta payload.
 */
fingerprint: string, serializedBytes: bigint,
/**
 * Production prompt input before provider-specific adaptation.
 */
normalizedInput: ContextInspectionCollection,
/**
 * Complete logical provider input after provider-specific adaptation.
 */
providerInput: ContextInspectionCollection, instructions: ModelRequestComponentSummary | null, tools: ModelRequestValueCollectionSummary | null, outputSchema: ModelRequestComponentSummary | null, };
